language: node_js
node_js:
  - 12

branches:
  only:
  - master
  - v1.x.x

jobs:
  include:
    - stage: test
      before_script:
        - npm run build
      script:
        - npm run test
      after_success:
        - npm run release